# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod/Dockerfile

tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install pulumi pulumi_akamai

  - name: Use Pulumi
    command: pulumi login
ports:
  - port: 5000
    onOpen: ignore

