# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod/Dockerfile

tasks:
  - name: Use Pulumi
    command: pulumi login
ports:
  - port: 5000
    onOpen: ignore

