---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod/Dockerfile

tasks:
  - init: |
      python -m pip install --upgrade pip
      virtualenv venv 
      pip install pulumi pulumi_akamai

  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Pulumi
    command: pulumi login
ports:
  - port: 5000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - kevinrose.vsc-python-indent
    - magicstack.magicpython
